title: HRC.ART Blog
description: Thoughts on art, technology, and everything in between
url: "https://henrycondon.github.io"
baseurl: "/hrc.art/blog"

# Build settings
theme: minima

# Minima specific settings
minima:
  date_format: "%b %-d, %Y"
  skin: dark

# Custom settings
show_excerpts: true